### ISSUE TITLE
Hello, I have a question 

### ISSUE THREAD

**Issue by parkwonjae** [LiyingCheng95/IAM#1]
Hello, Liying Cheng.
first,  thank you for releasing the dataset. This dataset is interesting.
I read your paper to use the dataset. I've read it all, and I've got a question.

![image](https://user-images.githubusercontent.com/26290599/192668206-fb8ab9e4-11e2-432c-8aa1-c31825618372.png)

I wonder if the performance in Table 5 is dev data or test data performance.
If you have time, I would like you to reply.
Thank you.

**Comment by LiyingCheng95** [comment]
test set
