### ISSUE TITLE
代码复现问题

### ISSUE THREAD

**Issue by Zechang-Xiong** [LiyingCheng95/IAM#2]
您好。感谢您提供了如此有用的代码。我正在尝试复现您在CESC任务上的Multi-label模型结果。我使用了默认设置，发现我的结果比您在论文中的性能低了8个点。请问需要注意哪些设置呢？

**Comment by LiyingCheng95** [comment]
请问现在解决了吗

**Comment by Zechang-Xiong** [comment]
> 请问现在解决了吗

您好，已经解决了！非常感谢！
